### ISSUE TITLE
Improvements to the GitHub Community Standards

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#63]
This issue involves researching and implementing the standards required for open-source applications in the GitHub Community Standards.

Progress tracking is done through the following link:
https://github.com/afet-yonetim-sistemi/ays-be/community

---

**Resources:**
- https://opensource.guide
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/about-community-profiles-for-public-repositories

**Comment by Rapter1990** [comment]
@agitrubard @skayikci @microgenius I've tried to devise a template for Contributing.md in this project. Can you review it if possible?


# Contributing Guidelines

Thank you for considering contributing to the "afet-yonetim-sistemi" project! We appreciate your interest and welcome any contributions that can help us improve the project.

Please take a moment to review these guidelines before making any contributions. Following these guidelines will help you maintain a collaborative and inclusive environment for everyone involved.

## Table of Contents
- [How to Contribute](#how-to-contribute)
- [Reporting Issues](#reporting-issues)
- [Submitting Changes](#submitting-changes)
- [Code Style](#code-style)
- [Commit Messages](#commit-messages)
- [Testing](#testing)
- [Documentation](#documentation)
- [Community Guidelines](#community-guidelines)

## How to Contribute

To contribute to the project, please follow these steps:

1. Fork the repository to your GitHub account.
2. Create a new branch for your contribution:
   - Branch names should be descriptive and relate to the feature or bug you are addressing.
   - Use kebab case (e.g., `fix-bug`, `add-new-feature`).
3. Make your changes in the branch you created.
4. Test your changes thoroughly to ensure their work as expected.
5. Commit your changes with clear and concise messages (see [Commit Messages](#commit-messages) section for more details).
6. Push your changes to your forked repository.
7. Open a pull request (PR) against the `main` branch of the "afet-yonetim-sistemi" repository.
   - Provide a clear and detailed description of the changes you made in the PR.
   - Link any relevant issues or discussions in the PR description.

Once your PR is submitted, the project maintainers will review it and provide feedback. Be prepared to make additional changes based on the feedback received.

## Reporting Issues

If you encounter any bugs, have feature requests, or want to provide general feedback, please feel free to open an issue in the "afet-yonetim-sistemi" repository. When creating an issue, please provide as much detail as possible, including:

- A clear and descriptive title
- Steps to reproduce the issue
- Expected behavior
- Actual behavior
- Any error messages or logs

## Submitting Changes

When submitting changes, please ensure the following:

- Your code adheres to the project's [code style guidelines](#code-style).
- You have added appropriate tests for your changes (see [Testing](#testing)).
- The documentation has been updated, if necessary (see [Documentation](#documentation)).
- Your commits are clean and have clear commit messages (see [Commit Messages](#commit-messages)).

## Code Style

To maintain a consistent codebase, please follow the existing code style used in the project. If necessary, refer to any code style guidelines mentioned in the repository.

## Commit Messages

Writing clear and descriptive commit messages is essential for the maintainability of the project. Follow these guidelines when writing commit messages:

- Limit the subject line to 50 characters.
- Begin the subject line with a verb in the present tense (e.g., "Fix," "Add," "Update").
- Use the imperative mood (e.g., "Fix bug" instead of "Fixed bug").
- Provide additional details in the commit message body if necessary. Explain why the change was made and any relevant information for reviewers.

Example:

```
Add feature to handle user authentication

- Implemented a new module for user authentication
- Updated existing login page UI
- Added new API endpoint for user registration
```

## Testing

If you are contributing code changes, it is important to include appropriate tests to ensure the stability and functionality of the project. Follow these guidelines when writing tests:

- Write tests that cover the new code you have added or modified.
- Ensure your tests are easy to understand and maintain.
- Run the existing test suite before submitting your changes to make sure they haven't introduced any regressions.
- Provide instructions on how to run the tests if they require additional setup or specific commands.

## Documentation

Clear and up-to-date documentation is crucial for the project's users and contributors. If your contribution introduces new features, modifies existing functionality, or requires changes to the documentation, please make the necessary updates.

Follow these guidelines for documenting your changes:

- Update the relevant documentation files to reflect your changes.
- Write clear and concise explanations.
- Use code examples or screenshots, if appropriate, to enhance understanding.
- Proofread your documentation to ensure it is accurate and free of errors.

## Community Guidelines

In addition to the technical aspects, it is important to follow the community guidelines to maintain a positive and inclusive environment for all contributors.

- Be respectful and considerate of others' opinions and ideas.
- Be open to feedback and willing to collaborate with other contributors.
- Avoid personal attacks, offensive language, and harassment.
- If you notice any inappropriate behavior, report it to the project maintainers.

By adhering to these guidelines, we can work together to build a welcoming and productive community.

Thank you for your interest in contributing to the "afet-yonetim-sistemi" project! We appreciate your support and look forward to your contributions.

**Comment by Rapter1990** [comment]
@agitrubard @skayikci @microgenius I've tried to devise a template for `LICENCE.md` in this project. Can you review it if possible?


MIT License
===========

This project is licensed under the terms of the MIT license.

MIT License
-----------

SPDX short identifier: MIT

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

1. The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

2. The Software is provided "as is," without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages, or other liability, whether in an action of contract, tort, or otherwise, arising from, out of, or in connection with the Software or the use or other dealings in the Software.

3. Except as contained in this notice, the name(s) of the above copyright holders shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization.

4. Redistributions of any form whatsoever must retain the following acknowledgment: "This product includes software developed by the Afet Yönetim Sistemi project (https://github.com/Afet-Yonetim-Sistemi/ays-be/)."

5. Redistributions of any form whatsoever must also include a copy of this license document in the distribution.

If you have any questions or concerns regarding the licensing of this software, please contact the project team at <contact@afetyonetim.com>.

**Comment by Rapter1990** [comment]
@agitrubard  @skayikci  @microgenius I've tried to devise a template for `SECURITY.md` in this project. Can you review it if possible?

# Security Policy

At Afet Yönetim Sistemi (AYS), we take the security of our software and community seriously. We appreciate your efforts to responsibly disclose any security vulnerabilities you may find.

## Reporting a Vulnerability

If you believe you have discovered a security vulnerability or have concerns regarding the security of our project, please help us by disclosing it to us in a responsible manner. We encourage you to follow the guidelines outlined below.

To report a vulnerability:

1. Create a new issue in this repository to report the vulnerability. Please provide as much information as possible to help us understand and reproduce the issue.
2. If you believe the vulnerability may have sensitive implications, please encrypt your findings using our PGP key (available in the repository).
3. We will review your report and respond to it as quickly as possible.
4. We appreciate your patience and cooperation during the disclosure process.

## Bug Bounty Program

At this time, Afet Yönetim Sistemi (AYS) does not offer a formal bug bounty program for the project.

## Supported Versions

Please note that only the latest release of this project is officially supported with security updates. It is highly recommended to keep your software up-to-date with the latest version.

## Security Considerations

Here are some security considerations when using this project:

1. Always ensure that you are using the latest version of the project to benefit from security updates and bug fixes.
2. Regularly update your dependencies to include any security patches that may have been released.
3. Follow best practices for secure coding and deployment, such as using strong and unique passwords, enabling two-factor authentication, and limiting access privileges.
4. Be cautious of the data you input or share, especially when interacting with external systems or APIs.

## Contact

If you need to contact us regarding any security-related matters or have any questions about the security of this project, you can reach out to us at:

- Email: [iletisim@afetyonetimsistemi.com](mailto:iletisim@afetyonetimsistemi.com)

We kindly request that you refrain from spam, social engineering, or any other malicious activities. We appreciate your cooperation in keeping our community safe and secure.

Thank you for your contributions and for helping us maintain a secure ecosystem.
